from Recommender import Recommender

r = Recommender()
r.parseMovieDB("db/movies.dat", "db/user_ratedmovies-timestamps.dat")
print('____________________________________________________________')
r.averagePrediction(100)
print('____________________________________________________________')
r.averagePrediction(100, user='1')
print('____________________________________________________________')
r.ItemBasedPredictionFit(10, 0.3)
print('____________________________________________________________')
r.ItemBasedRecommendUser('1', n=10)
print('____________________________________________________________')
r.ItemBasedBest(n=5)
print('____________________________________________________________')
r.UserBasedPredictionFit(10, 0.3)
print('____________________________________________________________')
r.UserBasedBest(n=5)
print('____________________________________________________________')
r.UserBasedRecommendUser('54767', n=10) #6393, 54767
print('____________________________________________________________')
r.SlopeOnePredictionFit()
print('____________________________________________________________')
r.SlopeOneRecommendUser('1')
print('____________________________________________________________')